/* eslint-disable import/no-anonymous-default-export */
export default [
    {
        title: "Opening Ceremony",
        desc: "Welcome! Meet the students behind SF Hacks & the Sponsors of our event. This is where you will receive all the information about the event.",
        link: "https://youtu.be/xErQE22cRpE",
        start: new Date(2022, 2, 11, 16, 0, 0, 0),
        end: new Date(2022, 2, 11, 17, 0, 0, 0),
        time: "4:00 PM - 5:00 PM",
    },
    {
        title: "MIXER! Find your team",
        desc: "We will be hosting a mixer where hackers are able to find a team and chat!",
        link: "1",
        start: new Date(2022, 2, 11, 17, 0, 0, 0),
        end: new Date(2022, 2, 11, 18, 0, 0, 0),
        time: "5:00 PM - 6:00 PM",
    },
    {
        title: "Women in STEM Q&A",
        desc: "We are celebrating women during International Women’s Month! Join us in a panel where hackers are able to ask questions to 4 individuals working in the tech field. ",
        link: "1",
        start: new Date(2022, 2, 11, 18, 0, 0, 0),
        end: new Date(2022, 2, 11, 19, 0, 0, 0),
        time: "6:00 PM - 7:00 PM",
    },
    {
        title: "Website Mini Competition Q&A",
        desc: "The creators of our website are hosting a mini-competition where hackers are able to implement their own flare to our site.",
        link: "https://youtu.be/FQvEIKbCpyA",
        start: new Date(2022, 2, 11, 19, 0, 0, 0),
        end: new Date(2022, 2, 11, 19, 30, 0, 0),
        time: "7:00 PM - 7:30 PM",
    },
    {
        title: "Cybersecurity Case Study Workshop",
        desc: "Miguel Horta and Tashaun Hill will go over the basics of cybersecurity, working in the field, and go over an interactive case study. ",
        link: "https://youtu.be/JyFzn2kfWYA",
        start: new Date(2022, 2, 12, 8, 0, 0, 0),
        end: new Date(2022, 2, 12, 9, 0, 0, 0),
        time: "8:00 AM - 9:00 AM",
    },
    {
        title: "Intro to Game Development",
        desc: "Joyce Lee will go over the most important systems and concepts using Unreal Engine 4. Join her to bring your gamer ideas to life!",
        link: "https://youtu.be/P08Ght7eZIc",
        start: new Date(2022, 2, 12, 9, 0, 0, 0),
        end: new Date(2022, 2, 12, 10, 0, 0, 0),
        time: "9:00 AM - 10:00 AM",
    },
    {
        title: "Keynote Speaker - Uche Egonu",
        desc: "Uche Egonu is currently a Software Engineer at Omada Health. Learn more about his journey through the tech world!",
        link: "https://youtu.be/dZ5l3971srg",
        start: new Date(2022, 2, 12, 10, 0, 0, 0),
        end: new Date(2022, 2, 12, 10, 30, 0, 0),
        time: "10:00 AM - 10:30 AM",
    },
    // {
    //     title: "Website Development Workshop",
    //     desc: "TBD",
    //     link: "https://sfsu.zoom.us/j/88382459556?pwd=K1Rta25EM1loWW5IMWoyQkYxUVcwUT09",
    //     start: new Date(2022, 2, 12, 10, 30, 0, 0),
    //     end: new Date(2022, 2, 12, 11, 30, 0, 0),
    //     time: "10:30 AM - 11:30 AM",
    // },
    {
        title: "Interview Prep Workshop",
        desc: "Are you terrified of the tech interview process? Do you wish someone could just give you an end-to-end overview of what the whole process is like? Fatima Taj will give a walkthrough of tech interviews and the art of networking during COVID!",
        link: "https://youtu.be/ea72RWnR65k",
        start: new Date(2022, 2, 12, 12, 0, 0, 0),
        end: new Date(2022, 2, 12, 13, 0, 0, 0),
        time: "12:00 PM - 1:00 PM",
    },
    {
        title: "Intro to Machine Learning Workshop",
        desc: "Ahmed Asadi will discuss a deeper learning of how machine learning works, building an AI classifier system from scratch, and answer questions in regards to the “Best Use of ML” category!",
        link: "https://youtu.be/FLoApifdGHM",
        start: new Date(2022, 2, 12, 13, 0, 0, 0),
        end: new Date(2022, 2, 12, 14, 0, 0, 0),
        time: "1:00 PM - 2:00 PM",
    },
    {
        title: "Keynote Speaker - Christopher Thompson and Sandeep Bhimireddy",
        desc: "Chris and Sandeep will talk about their journey of creating their startup, FoodHaven! If you’re looking for inspiration in putting your ideas into action, this is a great speech for you. ",
        link: "https://youtu.be/51hMHi5wVWg",
        start: new Date(2022, 2, 12, 14, 30, 0, 0),
        end: new Date(2022, 2, 12, 15, 0, 0, 0),
        time: "2:30 PM - 3:00 PM",
    },
    {
        title: "Intro to Azure + Q&A Panel",
        desc: "Jon Kotker will show you how to access Microsoft Azure for free as a student and how to leverage the cool public APIs to empower your next project!",
        link: "https://youtu.be/ZmYZLXZ9SrI",
        start: new Date(2022, 2, 12, 15, 0, 0, 0),
        end: new Date(2022, 2, 12, 16, 0, 0, 0),
        time: "3:00 PM - 4:00 PM",
    },
    {
        title: "Blockchain Development Workshop",
        desc: "Alex Lewin will introduce how blockchain is used in our world and how to build a simple blockchain project.",
        link: "https://youtu.be/TMn8-clC4sk",
        start: new Date(2022, 2, 12, 16, 0, 0, 0),
        end: new Date(2022, 2, 12, 18, 0, 0, 0),
        time: "4:00 PM - 5:00 PM",
    },
    {
        title: "#BlackInTech Panel",
        desc: "Join us in a panel full of distinguished individuals that are continuously increasing the representation and participation of Black people in the technology industry.",
        link: "1",
        start: new Date(2022, 2, 13, 10, 0, 0, 0),
        end: new Date(2022, 2, 13, 11, 0, 0, 0),
        time: "10:00 AM - 11:00 AM",
    },
    {
        title: "Submission closes at 1:00 PM PST and Judging starts",
        desc: "Good luck everyone!",
        link: "1",
        start: new Date(2022, 2, 13, 13, 0, 0, 0),
        end: new Date(2022, 2, 13, 16, 0, 0, 0),
        time: "1:00 PM - 4:00 PM",
    },
    {
        title: "Closing Ceremony",
        desc: "Congratulations everyone! We hope you enjoyed SF Hacks 2022 and we can’t wait to see you all next year :) ",
        link: "1",
        start: new Date(2022, 2, 13, 16, 0, 0, 0),
        end: new Date(2022, 2, 13, 19, 0, 0, 0),
        time: "4:00 PM - 6:00 PM",
    },
];
